version: '3.8'
services:
    server:
        build:
            context: ./server
            dockerfile: scheduler/Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - ./server/scheduler:/app
        ports:
            - 8000:8000
    queue:
        build:
            context: ./server
            dockerfile: scheduler/Dockerfile
        command: 'php artisan queue:work'
        depends_on:
            - db
    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: main
            MYSQL_USER: admin
            MYSQL_ROOT: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
